---
- name: restart rsyncd
  service:
    name: "{{ rsyncd_service_name }}"
    state: restarted
    enabled: true

- name: restart cron
  service:
    name: "{{ cron_service_name }}"
    state: restarted
    enabled: true

